#!/bin/bash

# This is to demonstrate how I run bowite on paired-end GRO-seq data. 

module load bowtie2/2.1.0 samtools/0.1.19

bowtie2 -p 12 -x [genome file] -1 [fastq pair1] -2 [fastq pair2] -X 2000 --no-mixed --no-discordant | 
samtools sort -o [seed]_hg19_BT2_sorted.bam -@ 8 -m 1G -

exit;
